export const data = {
    title1: "Armable Una Habitación Propia:",
    text1: "En este espacio encontrarás (muy pronto) nuestro Armable de Una Habitación Propia en un formato listo para que lo imprimas y empieces a replicar el proyecto en tu comunidad.",
    text11: "Pero, ¿qué es el Armable de Una Habitación Propia?",
    text12: "Este armable está pensado exclusivamente para ti, para que construyas desde la simbología de una Habitación Propia un espacio seguro, esta representación a escala conecta los elementos de una habitación real con algunos conceptos claves de la educación sexual integral, de forma que nos ayude a crear mundos más equitativos, con menos violencia de género y donde podamos ser dueñas y dueños de nuestra sexualidad, allí, podrás vincular las reflexiones de los espacios formativos y resguardar información importante sobre tus Derechos sexuales y Derechos Reproductivos (DSDR). Esperamos que esta pequeña guarida te acompañe por mucho tiempo, la compartas con las personas cercanas y pueda reproducirse en todos los rincones que habitemos. ¡Te deseamos una buena estadía!",
    title2: "Planos de Una Habitación Propia",
    text2: "En este espacio encontrarás (muy pronto) los Planes de Una Habitación Propia en un formato listo para que lo imprimas y empieces a replicar el proyecto en tu comunidad.",
    text21: "Pero, ¿Qué son los Planos de Una Habitación Propia?",
    text22: "Es manual pedagógico encontrarás todo un mundo simbólico construído por jóvenes que creen firmemente en la necesidad de tener espacios seguros y propios para aprender, reflexionar y de-construir en torno a los Derechos y Salud Sexual y Reproductiva, es por eso que de manera colectiva nos hemos pensado una metodología única, metafórica y simbólica, que conecta los elementos de una habitación real con algunos conceptos claves de la educación sexual integral, de forma que nos ayude a crear mundos más equitativos, con menos violencia de género y donde podamos ser dueñas y dueños de nuestra sexualidad. Esperamos que estos Planos y el Armable de Una Habitación Propia les sean de mucha ayuda a jóvenes de toda Colombia y Latinoamérica, por eso, les invitamos a que aterricen este proyecto a las necesidades propias de sus territorios, ¡queremos ver muchas habitaciones seguras y diversas que nos conecten y transformen!"
}