const textItems = {
    paredes: "Construyendo las paredes: El primer paso para construir Una Habitación Propia es lanzar unas bases sólidas de protección y confianza que nos resguarden de los peligros e inseguridades que se encuentran fuera, por eso, empezamos nuestro proyecto construyendo unas paredes que nos resguarden, para propiciar un espacio de autoconocimiento en el cual les participantes puedan identificar mitos, imaginarios, sesgos personales y colectivos que se han construido dentro de su comunidad en torno a la sexualidad, de esta forma podrán sumergirse en reflexiones que les ayuden a conocerse mejor, a deconstruir lo que les hace daño a ellxs y lxs demás, y a reconstruir nuevas formas de vivir la sexualidad.",
    ventanas: "Ubicando las ventanas: Este taller busca identificar los tabúes propios y ajenos que lxs jóvenes han aprendido y asumido. De esta manera, a través del diálogo se logran debatir elementos históricos, culturales, sociales y religiosos que han permitido que los mitos, tabúes y paradigmas se instauren en nuestras vidas y los naturalicemos, este ejercicio permite sanar y renunciar a muchas de estas imposiciones que no nos han permitido tener un goce completo de nuestra sexualidad y derechos, de forma que nos permitimos abrir las ventanas, para tener una perspectiva más amplia y clara de lo que es la salud sexual y reproductiva",
    puertas: "Instalando la puerta: La puerta es el elemento que tenemos para decir qué entra, cómo entra, qué se queda afuera y qué debe quedarse adentro, por eso, en este momento ponemos como tema central el consentimiento, para ayudarnos a afinar nuestras miradas frente a las relaciones violentas que pasan ocultas bajo unas lógicas no consensuadas, para grabarnos que No es No, que el silencio es No, que el alicoramiento es No, que la duda es No, que un sí manipulado es No, y que sin consentimiento no hay lugar para el placer. En este taller, lxs jóvenes reflexionaron sobre la importancia del consentimiento y las implicaciones que trae no respetarlo, se comprometieron a ser más consientes frente a las señales no verbales o directas que sus parejas tienen, y sanaron algunas situaciones en las que se sintieron agredidxs.",
    camas: "Nos sentamos en la cama para propiciar un espacio de conocimiento y debate sobre los derechos sexuales y derechos reproductivos (DSDR), enfocando el debate a la importancia de apropiarnos y vivir a través de ellos, el placer. En este taller se implementa un juego de mesa propio de Una Habitación Propia que llamamos 'Hasta el Último Derecho', con el fin de que colectivamente incorporemos los DSDR para que no se nos vulneren nunca más, para ello, también se exponen las rutas de atención de violencias sexuales para que lxs jóvenes tengan herramientas concretas para promover un ambiente más juso en sus propias sexualidades y las de sus comunidades.",
    closet: "Este espacio pretende sensibilizar a lxs participantes acerca de las orientaciones e identidades de género y sexuales, así como de las intersecciones que ponen a diversas personas en posiciones de opresión y desigualdad. En el clóset, partimos de un escenario monocromático para reflexionar acerca de las diversidades y la imposibilidad de encajar a las personas en el deber ser, de esta manera, partimos de nuestro mantra 'para los gustos, los colores', para comprender que nuestras realidades están llenas de matices y diversidades, tal como el amalgama de colores de un arcoíris. Cada persona es diferente y habita un lugar diferente en el mundo, por eso debemos tener nuestras propias posibilidades de crecer y ser respetados y respetadas tal como somos."
} 

export default textItems;
